name: ABTPi18n CI/CD Enterprise Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/seazdev/abtpi18n-backend
  IMAGE_FRONTEND: ghcr.io/seazdev/abtpi18n-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_BACKEND }}:latest

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.IMAGE_FRONTEND }}:latest

      - name: Generate SBOM
        uses: anchore/syft-action@v0.17.0
        with:
          image: ${{ env.IMAGE_BACKEND }}:latest
          format: spdx-json
          output: sbom.json

      - name: Security scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_BACKEND }}:latest
          format: table
          exit-code: '0'
          ignore-unfixed: true

      - name: Sign image (keyless)
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.4.0"
      - run: |
          cosign sign --keyless ${{ env.IMAGE_BACKEND }}:latest
          cosign sign --keyless ${{ env.IMAGE_FRONTEND }}:latest

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key && chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          echo "${SSH_KEY_PASSPHRASE}" | ssh-add ssh_key
          ssh -o StrictHostKeyChecking=no -p ${DEPLOY_PORT} ${DEPLOY_USER}@${DEPLOY_HOST} <<'EOF'
            cd /opt/tradingbot_pro
            docker compose pull
            docker compose up -d
            docker system prune -af
          EOF
